## <div align="center"> TUGAS LAB IF540 MACHINE LEARNING </div>
### <div align="center"> WEEK [02] : [DATA PREPROCESSING] </div>

#### <div align="center"> Semester Ganjil 2022/2023 </div>

In [3]:
import datetime
import uuid    

# Fill in your name and NIM
myName = "Reinhard Javera Maheswara"
myNIM = "77732"

myDate = datetime.datetime.now()
myDevice = str(uuid.uuid1())

# Header
print("Name: \t\t{}".format(myName))
print("NIM: \t\t{}".format(myNIM))
print("Start: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Reinhard Javera Maheswara
NIM: 		77732
Start: 		2024-09-09 15:35:12.677345
Device ID: 	6e49baca-6e86-11ef-8f69-c02703192af7



---

### Dataset yang dipakai:

1. [Wine Quality Dataset] – sumber : [https://www.kaggle.com/datasets/yasserh/wine-quality-dataset]
2. [Steel Industry Energy Consumption] – sumber : [https://archive.ics.uci.edu/dataset/851/steel+industry+energy+consumption]

### Hasil kerja

In [4]:
from IPython.display import Image
%matplotlib inline

In [5]:
import pandas as pd
from io import StringIO
import sys
csv_data = \
'''
A, B, C, D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,
'''

df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
#Access the underlying numpy array
#via the 'values' attribute
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [7]:
#Remove rows that contain missing values
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [8]:
df.isnull().sum()

A     0
 B    0
 C    1
 D    1
dtype: int64

In [9]:
#Remove columns that contain missing values
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [10]:
#Only drop rows where all columns are NaN
df.dropna(how='all')

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [11]:
#Drop rows that have fever than 3 real values
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [12]:
#Only drop rows where NaN appear in specific columns (here: 'C')
#df.dropna(subset=['C'])

In [13]:
#Again: our original array
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [14]:
#Impute missing values via the column mean

from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [15]:
df.fillna(df.mean())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0

In [16]:
import pandas as pd
df= pd.DataFrame([['green', 'M', 10.1, 'class2'],
                  ['red', 'L', 13.5, 'class1'],
                  ['blue', 'XL', 15.3, 'class2']])

df.columns = ['color', 'size', 'price', 'classlabel']

In [17]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

df['size'] = df['size'].map(size_mapping)


In [18]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [19]:
import numpy as np

#Create a mapping dict
#to convert class labels from strings to integers
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}

In [20]:
#to convert class labels from string to integers
df['classlabel'] = df['classlabel'].map(class_mapping)

In [21]:
#Reverse the class label mapping
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)

In [22]:
from sklearn.preprocessing import LabelEncoder

#Label encoding with sklearn's LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [23]:
#Reverse mapping
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

In [24]:
X = df[['color', 'size', 'price']].values
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
X


array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [25]:
from sklearn.preprocessing import OneHotEncoder

X = df[['color', 'size', 'price']].values
color_ohe = OneHotEncoder()
color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [26]:
from sklearn.compose import ColumnTransformer

X = df[['color', 'size', 'price']].values
c_transf = ColumnTransformer([ ('onehot', OneHotEncoder(), [0]),
                               ('nothing', 'passthrough', [1, 2])])

In [27]:
#One-hot encoding via pandas
pd.get_dummies(df[['price', 'color', 'size']])

price  size  color_blue  color_green  color_red
0   10.1     1       False         True      False
1   13.5     2       False        False       True
2   15.3     3        True        False      False

In [28]:
#multicollinearity guard in get_dummies
pd.get_dummies(df[['price', 'color', 'size']], drop_first=True)

price  size  color_green  color_red
0   10.1     1         True      False
1   13.5     2        False       True
2   15.3     3        False      False

In [29]:
#multicollinearity guard for the OneHotEncoder
color_ohe = OneHotEncoder(categories='auto', drop='first')
c_transf = ColumnTransformer([('onehot', color_ohe, [0]),
                              ('nothing', 'passthrough', [1, 2])])
c_transf.fit_transform(X).astype(float)


array([[ 1. ,  0. ,  1. , 10.1],
       [ 0. ,  1. ,  2. , 13.5],
       [ 0. ,  0. ,  3. , 15.3]])

In [30]:
df_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

#if the Wine dataset is temporarily unavailable from the UCI Machine Learning repository, un-comment the following line of code to load the dataset from a local path:

# df_wine = pd.read_csv('wine.data', header=None)

df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                  'Alcalinity of ash', 'Magnesium', 'Total phenols',
                  'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                  'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                  'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

Class labels [1 2 3]


Class label  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0            1    14.23        1.71  2.43               15.6        127   
1            1    13.20        1.78  2.14               11.2        100   
2            1    13.16        2.36  2.67               18.6        101   
3            1    14.37        1.95  2.50               16.8        113   
4            1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [31]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test = \
    train_test_split(X, y,
                     test_size=0.3,
                     random_state=0,
                     stratify=y)

In [32]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [33]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [34]:
ex = np.array([0, 1, 2, 3, 4, 5])

print('standardized:', (ex - ex.mean()) / ex.std())

# normalize
print('normalized:', (ex - ex.min()) / (ex.max() - ex.min()))

standardized: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
normalized: [0.  0.2 0.4 0.6 0.8 1. ]


<h3>Dataset Pertama: Wine Quality Dataset</h3>

In [35]:
from IPython.display import Image
%matplotlib inline

In [36]:
import pandas as pd
import sys

df = pd.read_csv('E:/_Kuliah/Semester 5/Machine Learning/Week2/WineQT.csv')

In [37]:
#Access the underlying numpy array
#via the 'values' attribute
df.values

array([[7.400e+00, 7.000e-01, 0.000e+00, ..., 9.400e+00, 5.000e+00,
        0.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, ..., 9.800e+00, 5.000e+00,
        1.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, ..., 9.800e+00, 5.000e+00,
        2.000e+00],
       ...,
       [6.200e+00, 6.000e-01, 8.000e-02, ..., 1.050e+01, 5.000e+00,
        1.594e+03],
       [5.900e+00, 5.500e-01, 1.000e-01, ..., 1.120e+01, 6.000e+00,
        1.595e+03],
       [5.900e+00, 6.450e-01, 1.200e-01, ..., 1.020e+01, 5.000e+00,
        1.597e+03]])

In [38]:
#Remove rows that contain missing values
df.dropna(axis=0)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [39]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [40]:
#Remove columns that contain missing values
df.dropna(axis=1)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [41]:
#Only drop rows where all columns are NaN
df.dropna(how='all')

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [42]:
#Drop rows that have fever than 3 real values
df.dropna(thresh=4)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [43]:
#Only drop rows where NaN appear in specific columns (here: 'C')
df.dropna(subset=['residual sugar'])

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [44]:
#Again: our original array
df.values

array([[7.400e+00, 7.000e-01, 0.000e+00, ..., 9.400e+00, 5.000e+00,
        0.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, ..., 9.800e+00, 5.000e+00,
        1.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, ..., 9.800e+00, 5.000e+00,
        2.000e+00],
       ...,
       [6.200e+00, 6.000e-01, 8.000e-02, ..., 1.050e+01, 5.000e+00,
        1.594e+03],
       [5.900e+00, 5.500e-01, 1.000e-01, ..., 1.120e+01, 6.000e+00,
        1.595e+03],
       [5.900e+00, 6.450e-01, 1.200e-01, ..., 1.020e+01, 5.000e+00,
        1.597e+03]])

In [45]:
#Impute missing values via the column mean

from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[7.400e+00, 7.000e-01, 0.000e+00, ..., 9.400e+00, 5.000e+00,
        0.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, ..., 9.800e+00, 5.000e+00,
        1.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, ..., 9.800e+00, 5.000e+00,
        2.000e+00],
       ...,
       [6.200e+00, 6.000e-01, 8.000e-02, ..., 1.050e+01, 5.000e+00,
        1.594e+03],
       [5.900e+00, 5.500e-01, 1.000e-01, ..., 1.120e+01, 6.000e+00,
        1.595e+03],
       [5.900e+00, 6.450e-01, 1.200e-01, ..., 1.020e+01, 5.000e+00,
        1.597e+03]])

In [46]:
df.fillna(df.mean())

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

<h3>Dataset Kedua: Steel Industry Energy Consumption</h3>

---

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
# 1. Load the Dataset
# Make sure to replace 'Steel_industry_data.csv' with the correct file path if necessary
df = pd.read_csv('E:/_Kuliah/Semester 5/Machine Learning/Week2/Steel_industry_data.csv')
# 2. Convert 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y %H:%M')
# 3. Extract useful features from the 'date' column
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
# 4. Drop the original 'date' column as it's now redundant
df.drop(columns=['date'], inplace=True)
# 5. Separate the target variable 'Load_Type'
y = df['Load_Type'] # Target variable
# 6. Drop 'Load_Type' from the DataFrame to prepare features
X = df.drop('Load_Type', axis=1)
# 7. Convert categorical variables to numeric using one-hot encoding
X = pd.get_dummies(X, columns=['WeekStatus', 'Day_of_week'], drop_first=True)
# 8. Convert target variable to numeric (Label Encoding)
y = y.map({'Light_Load': 0, 'Medium_Load': 1, 'Maximum_Load': 2})
# 9. Scale Numerical Features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# 10. Split the Dataset into Training and Test Sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=0, stratify=y)
# 11. Train a RandomForest Model to Determine Feature Importance
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(X_train, y_train)
# 12. Use the Trained Model to Select Important Features
model = SelectFromModel(clf, prefit=True)
X_train_selected = model.transform(X_train)
X_test_selected = model.transform(X_test)
# 13. Print Results
print("Original number of features:", X_train.shape[1])
print("Reduced number of features:", X_train_selected.shape[1])


Original number of features: 18
Reduced number of features: 5


In [48]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
# Load the dataset
df = pd.read_csv('Steel_industry_data.csv')


In [49]:
# Check for missing values
print("Missing values in each column:\n", df.isnull().sum())
# Impute missing values with the mean for numerical columns
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
df[numerical_columns] = imputer.fit_transform(df[numerical_columns])
# Check for remaining missing values (should be zero)
print("Remaining missing values after imputation:\n", df.isnull().sum())


Missing values in each column:
 date                                    0
Usage_kWh                               0
Lagging_Current_Reactive.Power_kVarh    0
Leading_Current_Reactive_Power_kVarh    0
CO2(tCO2)                               0
Lagging_Current_Power_Factor            0
Leading_Current_Power_Factor            0
NSM                                     0
WeekStatus                              0
Day_of_week                             0
Load_Type                               0
dtype: int64
Remaining missing values after imputation:
 date                                    0
Usage_kWh                               0
Lagging_Current_Reactive.Power_kVarh    0
Leading_Current_Reactive_Power_kVarh    0
CO2(tCO2)                               0
Lagging_Current_Power_Factor            0
Leading_Current_Power_Factor            0
NSM                                     0
WeekStatus                              0
Day_of_week                             0
Load_Type                    

In [50]:
# Convert 'date' column to datetime format and extract features
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y %H:%M')
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
# Drop the original 'date' column
df.drop(columns=['date'], inplace=True)


In [51]:
# Encode 'WeekStatus' and 'Day_of_week' using one-hot encoding
df = pd.get_dummies(df, columns=['WeekStatus', 'Day_of_week'], drop_first=True)
# Encode 'Load_Type' (target variable) using label encoding
class_le = LabelEncoder()
df['Load_Type'] = class_le.fit_transform(df['Load_Type'])


In [52]:
# Separate features (X) and target (y)
X = df.drop('Load_Type', axis=1) # Features
y = df['Load_Type'] # Target variable
# Scale the features using Min-Max scaling
mms = MinMaxScaler()
X_norm = mms.fit_transform(X)
# Alternatively, standardize the features
stdsc = StandardScaler()
X_std = stdsc.fit_transform(X)
# Example to print normalized and standardized data
print("Normalized Data Sample:\n", X_norm[:5])
print("Standardized Data Sample:\n", X_std[:5])


Normalized Data Sample:
 [[0.02016796 0.03044062 0.         0.         0.7321     1.
  0.01052632 0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.         0.        ]
 [0.02544853 0.04602208 0.         0.         0.6677     1.
  0.02105263 0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.         0.        ]
 [0.02061331 0.03384584 0.         0.         0.7028     1.
  0.03157895 0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.         0.        ]
 [0.02105866 0.03673512 0.         0.         0.6809     1.
  0.04210526 0.         0.         0.         0.04347826 0.
  1.         0.         0.         0.         0.         0.        ]
 [0.02430335 0.04643484 0.         0.         0.6472     1.
  0.05263158 0.         0.         0.         0.04347826 0.
  1.         0.         0.         0.         0.         0.        ]]
Standardized Data Sample:
 [[

In [53]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.3, random_state=0, stratify=y)
print("Training and testing data prepared.")

Training and testing data prepared.


### Kesimpulan



Berikan simpulan yang dilakukan dari hasil kerja menggunakan algoritma dan 2 dataset yang
dipilih. Simpulan bisa berkisar antara (bisa di modifikasi):

    - Simpulan perbandingan dataset
    
    - Hasil pemikiran dan observasi akhir dari kerja menurut mahasiswa.

In [54]:
output = """
Kesimpulan:
1. Perbandingan dataset
Steel Industry Energy Consumption Dataset ini berfokus pada konsumsi energi di industri baja, dengan fitur yang mencakup nilai-nilai temporal dan numerik. 
Preprocessing dilakukan dengan penanganan nilai hilang melalui imputasi rata-rata, serta ekstraksi fitur waktuyang memungkinkan analisis pola temporal. 
Sedangkan Wine Quality Dataset Dataset ini berkaitan dengan varian merah dari anggur "Vinho Verde" asal Portugal. 
Dataset ini menggambarkan jumlah berbagai bahan kimia yang ada dalam anggur dan pengaruhnya terhadap kualitas anggur tersebut. 
Dataset ini bisa dilihat sebagai tugas klasifikasi atau regresi. Kelas-kelasnya terurut dan tidak seimbang 
(misalnya, ada lebih banyak anggur yang kualitasnya biasa-biasa saja dibandingkan dengan yang kualitasnya luar biasa atau buruk).

2. Hasil pemikiran dan observasi
Preprocessing data memainkan peran penting dalam memastikan bahwa dataset siap digunakan untuk pengembangan model. 
Penanganan nilai hilang, penskalaan fitur, dan pengkodean kategorikal adalah langkah-langkah krusial yang meningkatkan efektivitas model
prediktif. Dengan dataset yang telah diproses dengan baik, fokus selanjutnya dapat diarahkan pada eksperimen dengan berbagai algoritma machine learning 
untuk mendapatkan model dengan kinerja terbaik.

"""
print(output)


Kesimpulan:
1. Perbandingan dataset
Steel Industry Energy Consumption Dataset ini berfokus pada konsumsi energi di industri baja, dengan fitur yang mencakup nilai-nilai temporal dan numerik. 
Preprocessing dilakukan dengan penanganan nilai hilang melalui imputasi rata-rata, serta ekstraksi fitur waktuyang memungkinkan analisis pola temporal. 
Sedangkan Wine Quality Dataset Dataset ini berkaitan dengan varian merah dari anggur "Vinho Verde" asal Portugal. 
Dataset ini menggambarkan jumlah berbagai bahan kimia yang ada dalam anggur dan pengaruhnya terhadap kualitas anggur tersebut. 
Dataset ini bisa dilihat sebagai tugas klasifikasi atau regresi. Kelas-kelasnya terurut dan tidak seimbang 
(misalnya, ada lebih banyak anggur yang kualitasnya biasa-biasa saja dibandingkan dengan yang kualitasnya luar biasa atau buruk).

2. Hasil pemikiran dan observasi
Preprocessing data memainkan peran penting dalam memastikan bahwa dataset siap digunakan untuk pengembangan model. 
Penanganan nilai hilang

In [55]:
# Footer
myDate = datetime.datetime.now()
print("I certify that this is my own work.")
print("Signed by:")
print("Name: \t{}".format(myName))
print("NIM: \t{}".format(myNIM))
print("Time-stamp:\t{}".format(myDate))

I certify that this is my own work.
Signed by:
Name: 	Reinhard Javera Maheswara
NIM: 	77732
Time-stamp:	2024-09-09 15:35:18.204270


***

### Save the notebook, then convert the notebook to html (by running the next code).

In [56]:
!jupyter nbconvert --to html "./IF540L_H_laporan_M02_00000077732_Reinhard Javera Maheswara.ipynb" --output-dir="./"

This application is used to convert notebook files (*.ipynb)
        to various other formats.


Options
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePr

[NbConvertApp] WARNING | pattern './IF540L_H_laporan_M01_NIM_NAMA.ipynb' matched no files


### Next step:
* convert the generated html file to PDF using the online tool: https://www.sejda.com/html-to-pdf
* choose the following settings:
    * Page size: One long page
    * Page Orientation: auto
    * Use print stylesheet
* Submit your ipython notebook and PDF files

Markdown basics https://markdown-guide.readthedocs.io/en/latest/basics.html#